### PR TITLE
Bug Fixes

### LINKED ISSUE #1073: Building Investigate Count <0? on starting a mission at a building where agents are already present
**Describe the bug**
Agents are already commanded to move to an apartment and wait for a alien alert (load the game and ultra fast time)
When the alert appears I select the agents already there to investigate
The following error occurs on confirming the order to investigate
image
Clicking okay will continue the investigation
But something is amiss to cause this

**Savegame**
[save_Economy 1.zip](https://github.com/OpenApoc/OpenApoc/files/7446764/save_Economy.1.zip)

### PR DESCRIPTION
**Pull request by kgd192**
Fix #1073 

Unfortunately due to how Event handling works I am currently unabel to provide a more elegant solution

### CODE REVIEW

**Comment by kgd192** [comment]
Fix #484 (Partially)

Recovery Vehicles could not reach other crashed vehicles since their tiles wher marked unreachable due to having no landing Pad, this is now fixed.
Additionaly, AI vehicles which gave up on routefinding during their way home do now crash to initiate recovery by the AI.
No Fixed were attempted regarding the issue that destroyed vehicles are not removed correctly

**Comment by FilmBoy84** [comment]
Much appreciated on your continued PRs 🍻 

I apologise for the continued Linting errors that stop us merging - I've asked another member of the team to look into it when they are able.

I agree on the fix for #1073 and can also not see a better solution at present

**Comment by kgd192** [comment]
> I apologise for the continued Linting errors that stop us merging - I've asked another member of the team to look into it when they are able.

No worries it will be figured out eventually.

For the #484 , One addition I could think of is to give the vehicles a certain time they have to be in a "lost can not find way home state" before they are flagged as damaged and eventually recovered. I honestly didn't check (if even feasible) how the original game handled stuck vehicles.

**Comment by FilmBoy84** [comment]
> For the #484 , One addition I could think of is to give the vehicles a certain time they have to be in a "lost can not find way home state" before they are flagged as damaged and eventually recovered. I honestly didn't check (if even feasible) how the original game handled stuck vehicles.

From what I remember of last time i looked into this: The original game differs in that it only generates missions from point a to b (typically garage to garage or hanger to hanger) rather than the variety of missions we have as optional in OpenApoc (for example via the "Realistic Transportation" feature)

If the target garage or hanger is destroyed whilst the mission is in progress, the vehicle is simply rerouted to it's point of origin or an alternative friendly garage or hanger to the original target within 20 tiles (decision is RNG based with a bias to minimal pathfinder cost)

Given OpenApoc users may be playing without "Realistic Transportation" enabled, that should be replicated for those users.

For users with "Realistic Transportation" enabled we have a few more options as follows

* Behaviour as per above (OG)
* Create entirely new mission, changing direction accordingly
* Attack the unit or organisation that caused damage to the target tile until target destroyed, vehicle destroyed, or it is forced to crash or return to original point of origin
* Choose to "Raid" the organisation (or allies of the organisation) that attacked the target garage or hanger
* Crash the vehicle (maybe they just had a traffic accident) and allow the recovery mechanic to order a recovery unit to collect it and return to the parent organisation

**Comment by kgd192** [comment]
> * Crash the vehicle (maybe they just had a traffic accident) and allow the recovery mechanic to order a recovery unit to collect it and return to the parent organisation.

That was my thought process as well that the vehicle did basicaly break down at the side of the road and then be recovered so that the city would not fill up w/ stuck vehicles.

Otherwise if their current mission is canceled the current behavior that they simply return home remains.

But I really like the Idea to expand on that and create follow on missions depending on why the mission was canceled.

**Comment by FilmBoy84** [comment]
Getting a linting error still

Are you running a CLANG format pass with CLANG / LLVW 14 before submitting each commit?

`for /R forms %%f in (*.cpp,*.h) do clang-format -i "%%f"
for /R framework %%f in (*.cpp,*.h) do clang-format -i "%%f"
for /R game %%f in (*.cpp,*.h) do clang-format -i "%%f"
for /R library %%f in (*.cpp,*.h) do clang-format -i "%%f"
for /R tools %%f in (*.cpp,*.h) do clang-format -i "%%f"

del *.TMP /F /S`

**Comment by kgd192** [comment]
> Getting a linting error still
> 
> Are you running a CLANG format pass with CLANG / LLVM 14 before submitting each commit?

Actually I did not, I will recheck and probably upload the changes to sepperate Branches

**Comment by FilmBoy84** [comment]
> > Getting a linting error still
> > Are you running a CLANG format pass with CLANG / LLVM 14 before submitting each commit?
> 
> Actually I did not, I will recheck and probably upload the changes to sepperate Branches

Thanks, yeah, seperate commits for each fix/change makes things much easier if we have to review at a later point

I'm around for the next hour or so so fingers crossed if we can resolve the linting errors I can review and merge today :)

**Comment by kgd192** [comment]
Have been separated in different Branches / Pull Request #1136 and #1137

**Comment by kgd192** [comment]
Haven been separated into individuall pull requests #1136 & #1137

**Pull request closed without merging**
