### PR TITLE
implemented the ScoreScreen

### PR DESCRIPTION
**Pull request by redv**
implemented the ScoreScreen

score1_openapoc

score2_openapoc

### CODE REVIEW

**Comment by makus82** [comment]
beauty =]

**Comment by makus82** [comment]
so its only screen or whol week funding mechanics?

**Comment by redv** [comment]
Its only the screens. The screen just recieves data from internal structures of data. So, need to write code to collect these data properly. At this point only the score of tactical missions works.

**Comment by redv** [comment]
And looks like i broke the ubuntu and travis again :)

**Comment by redv** [comment]
At this moment the score counts for:
- tactical missions;
- finished researches;
- alien incidents;
- city damages.

score1_openapoc_inc

**Comment by JonnyH** [comment]
@redv Thanks for all the good work -  sorry I'm bottlenecking the merging!

So I'm going to give you commit access - so feel free to merge your own stuff!

But generally it's a good idea to open a PR, as it runs the travis builds, and make sure the lint pass that runs clang-format is correct! I like formatting :)

And going forward, feel free to review and comment on anyone's PRs, and feel free to merge if you think they're clearly good!

**Comment by redv** [comment]
Thanks.

**Pull request merged**
