### PR TITLE
fixed the mission RecoverVehicle

### PR DESCRIPTION
**Pull request by redv**
fixed issue #255 "Emergency Vehicles do not pick up crashed road vehicles".

### CODE REVIEW

**Comment by FilmBoy84** [comment]
Many thanks @redv for fixing this, i shall get right into testing this evening and report back on issue #260 / #317 as well as check that #255 is totally resolved before letting you know.

**Comment by FilmBoy84** [comment]
@redv 
Have left an update to #255 regarding smoke not disappearing.
Have also introduced a new issue #332 that has started to occur in the most recent 0.1-169 version.

**Comment by redv** [comment]
fixed issue #332 "No vehicle matching pointer". Its because CoS tries to loot UFOs.
fixed issue #333 "City Organisations recover UFOs before X-COM". Because CoS rescue allied Aliens.

**Comment by redv** [comment]
fixed smoke issue as described in #255 
This fix will work only for newly crashed vehicles or a new game.

**Pull request merged**
