### PR TITLE
Update libsmacker

### PR DESCRIPTION
**Pull request by JonnyH**
This contains a palette aliasing fix - maybe helps with issue #826

### CODE REVIEW

**Comment by Atrosha** [comment]
Regression test failed.

**Comment by Atrosha** [comment]
The same with newest changes.

Also... Is `WIP/allow-overlapping-palette-copies` branch needs to be tested?

**Comment by JonnyH** [comment]
Make sure you've updated the dependencies - 'git submodule update --init' should be enough after a checkout.

git by default doesn't change submodules on parent checkout, though some git wrappers do (the inconsistency makes it more annoying than anything)

After the checkout and submodule update,the dependencies/libsmacker version should be 21332e23e4937cd13b2faf39678ff473866b327b ("Don't skip palette copies with overlapping src/dst regions") - which is on the WIP/allow-overlapping-palette-copies branch of the libsmacker repo - though you should rely on the 'git submodule' command to ensure you have the correct version (and 'git status' should not say that the dependencies/libsmacker directory has changed)

**Comment by Atrosha** [comment]
It's my fault, sorry. After `git submodule update --init --recursive` all fine.

Screenshot from 2020-04-21 22-54-28

And finally regression test **passed**.

**Pull request merged**
