### PR TITLE
Fix BaseScreen not highlighting correct base

### LINKED ISSUE #1298: Buy Sell With Multiple Bases Bug
When you have multiple bases, the initially selected base before you go into the Buy Sell window appears to be the only base that has its inventory displayed. When switching to the other base, it still shows the initial base's inventory. A second bug is combined with this. When you exit back to the Bases screen, the bases in the top left corner have nothing selected, and the base layout and base name do not match. Please see https://www.twitch.tv/videos/2014685651 for an in-depth test. This is with build 20231214B along with EWM mod music mod.
[Buy Sell Bug With Multiple Bases.zip](https://github.com/OpenApoc/OpenApoc/files/13774457/Buy.Sell.Bug.With.Multiple.Bases.zip)

### PR DESCRIPTION
**Pull request by Kurtsley**
Fixes #1298 and #1392

This restores the functionality of the original game. In the transfer, buy and sell, and alien containment screens, you will be returned to the original base that was selected from the base screen. In the research screen, you will be transferred to the base you select regardless of the original selection. Not sure if this is desired but this does fix bases not being highlighted as well. If it would be better to unify the behavior for all screens, it would be an easy fix.

### CODE REVIEW

**Comment by Kurtsley** [comment]
Strange, I formatted this in Visual Studio and it still failed.

**Comment by FilmBoy84** [comment]
> Strange, I formatted this in Visual Studio and it still failed.

Are you on LLVM/Clang 14?

**Comment by Kurtsley** [comment]
Not sure, I've never bothered with that before. I'll try in Linux.

**Comment by Kurtsley** [comment]
I just ran clang-format from WSL and copied the file over. Same exact results.

**Comment by FilmBoy84** [comment]
Thanks for this fix Kurtsley, tested and merging 🍻 

I'll have a think about unification of functionality - for now it matches OG which is the priority

What was the resolution to the Linting issue btw?

**Comment by Kurtsley** [comment]
I just copied the entire file from github and made my change without formatting the file on my end.

**Pull request merged**
