### PR TITLE
Warning all weapon ammo types that needs to be researched before using

### PR DESCRIPTION
**Pull request by ayrtondenner**
Following with #1455, game will now inform user all the ammo types that needs to be researched together with weapon before you can be able to use it.

Also updated `tryPickUpItem` to not only return pickup result but also which item was selected.

Example where Brainsucker Launcher is researched, but Brainsucker Pod is not:
image

Let's say that a weapon has multiple ammo types. Warn message will properly display list of ammo types that need to be researched:
image

Items that are not weapon, or weapon with no ammo type will display default message. Example with Disruptor Gun:
image

### CODE REVIEW

**Comment by FilmBoy84** [comment]
Thanks for this 🍻 

Reading though - LGTM

I'm compiling now and will get on testing tomorrow

**Comment by XCOM-HUB** [comment]
The name of the Brainsucker Launcher should be revealed after you have only researched the Brainsucker Launcher, but the prompt that says that you need to also reaserch the Brainsucker Pods should still be in. I also think you should be able to sell the Brainsucker Launcher after only having researched the Brainsucker Launcher.

**Comment by ayrtondenner** [comment]
> The name of the Brainsucker Launcher should be revealed after you have only researched the Brainsucker Launcher, but the prompt that says that you need to also research the Brainsucker Pods should still be in.

Addressed in https://github.com/OpenApoc/OpenApoc/pull/1472

**Comment by ayrtondenner** [comment]
> I also think you should be able to sell the Brainsucker Launcher after only having researched the Brainsucker Launcher.

@XCOM-HUB I just tested it and I was able to sell Brainsucker Launcher after having it researched but not Brainsucker. Can you test it again with current version?

image
image

**Comment by XCOM-HUB** [comment]
Yes! I can confirm that you can sell the Brainsucker Launchers now without also having to wait for the Brainsucker Pods to be fully researched. Thank you for your work and dedication to the OpenApoc project 👍 @ayrtondenner

**Pull request merged**
