### PR TITLE
Live alien recovery after base defense battle

### LINKED ISSUE #1422: Capturing Live Aliens in a Base Attack Mission will come up as 0 in the [DEBRIEFING]
- OS: Windows 11 Pro x64 23H2
 - OpenApoc Version: [0.0.1038](https://ci.appveyor.com/project/OpenApoc/openapoc/builds/49642396)
 - No Mods

When my base was under attack I successfully captured one living Chrysalis, but the [DEBRIEFING] states that I haven't captured any live aliens. When un-pausing in Cityscape I get four messages that I have retrieved items from tactical combat zone and I can clearly see that I have a live Chrysalis in my Alien Containment.

Skärmbild 2024-04-18 201643
Skärmbild 2024-04-18 172021

When completing a mission elsewhere you only get one message about items arriving at your base:

Skärmbild 2024-04-18 171528

SAVE-FILE in Battlescape (Just end the turn and let my Laser Turrets kill one Spitter and one Hyperworm): 
[Base Under Attack Battlescape 3.zip](https://github.com/OpenApoc/OpenApoc/files/15029387/Base.Under.Attack.Battlescape.3.zip)

### PR DESCRIPTION
**Pull request by ayrtondenner**
Fixes #1422

Now, after finishing a Base Defense battle, live aliens will be considered for score calculation, and they will NOT be send to any vehicle, but will be added to base alien storage instead.

Updates list:
- For score math, live aliens will be considered if mission is a base defense and base has alien storage **OR** if mission has player craft with available bio storage.
- Similarly, live aliens will be set as "leftover" only when **BOTH** conditions above are false.
- At `battle.cpp`, instructions inside `if (!playerVehicles.empty())` and `for (auto &v : playerVehicles)` will only be executed when mission is **NOT** a base defense one. Since both instruction groups deal with adding stuff at vehicles to be send to base, it seems that they shouldn't execute when defending a base. Let me know if that's correct or needs to be changed.
- Minor refactors merging nested if conditions that could be represented at same if statement

I didn't add any alien storage limit check when recovering live aliens, since it seems we don't have any limit enforcing right now.

Also, I guess that to fix equipment issue reported in #1333, similar changes must be done but regarding item loot instead.

### CODE REVIEW

**Comment by XCOM-HUB** [comment]
I have just tried your latest fix, and it works 🎊🎉👍

**Comment by ayrtondenner** [comment]
Thanks @XCOM-HUB , were you able to check if it didn't mess up any logic for other mission types? I want to be sure that older logic of shipping living aliens via vehicles bio storage is still properly working.

**Comment by XCOM-HUB** [comment]
I just did a UFO crash mission and everything seemed to work. Live Aliens were captured and the score for capturing Live Aliens seemed to be accurate. I couldn't see anything wrong with your fix ( [0.0.1065](https://ci.appveyor.com/project/OpenApoc/openapoc/builds/49844216) )

**Comment by FilmBoy84** [comment]
> I just did a UFO crash mission and everything seemed to work. Live Aliens were captured and the score for capturing Live Aliens seemed to be accurate. I couldn't see anything wrong with your fix ( [0.0.1065](https://ci.appveyor.com/project/OpenApoc/openapoc/builds/49844216) )

Were aliens still added to vehicles before being added to base on return?

**Comment by XCOM-HUB** [comment]
The Live Aliens were retrieved from the mission, and put in Alien Containment because I saw them once my vehicle arrived at my base. I don't know if there is a way to see if there is any Live Aliens inside of my vehicles biological storage directly after the mission. I have to check that.

**Comment by FilmBoy84** [comment]
> The Live Aliens were retrieved from the mission, and put in Alien Containment because I saw them once my vehicle arrived at my base. I don't know if there is a way to see if there is any Live Aliens inside of my vehicles biological storage directly after the mission. I have to check that.

Easiest way to check would be to do a UFO recovery with a bio transport module
On mission end BEFORE vehicle returns to base, check alien containment - captured aliens should not be there yet
When the vehicle returns they should be there

This PR aims to fix Base Defence missions - on completion the aliens should automatically go to the alien containment regardless of vehicles / bio transport modules being present

What we also need to check is that if there is NO alien containment they will be sent to a vehicle with a bio transport module

If no alien containment is present and no vehicle with a bio transport module is present then the aliens should be destroyed with no points for recovery

**Comment by XCOM-HUB** [comment]
The Live Aliens did not go straight to my base after doing a UFO crash site mission. Both dead and alive aliens were added to my Alien Containment in base after the vehicle returned to base. I have double checked it.

**Comment by FilmBoy84** [comment]
All checks passed, LGTM, merging

Thanks as always for working on this 🍻

**Comment by XCOM-HUB** [comment]
Aliens won't be added to the Bio-Transport Module if you don't have any Alien Containment in your bases (regular mission in a building not owned by X-Com).

SAVE-FILE: [At least one Live Alien.zip](https://github.com/user-attachments/files/15805495/At.least.one.Live.Alien.zip)

**Pull request merged**
