### PR TITLE
Notify road segment of a road tile repair to restore its passability.

### PR DESCRIPTION
**Pull request by emptyVoid**
Related to #339.

### CODE REVIEW

**Comment by FilmBoy84** [comment]
Oh, interesting find and thanks for the fix

So that's why, even though the road appears to be there visually, vehicles won't pass on it? - for traversing purposes it's not recognised as passable

Great work emptyvoid

Will build and test shortly and merge as appropriate

**Comment by emptyVoid** [comment]
Yeah, the road segments for collapsed CoS Temple garages kept reporting their road tiles as not intact even after the Temples got reconstructed at the end of day.

**Comment by FilmBoy84** [comment]
Out of interest is this also the potential cause for buildings that are collapsed and are rebuilt still acting as though collapsed in some instances?

I suspect if a bug exists with road, there is likely one similar in building tiles; it would explain some of the odd things in the save in #843 despite that issue dealing with another problem

**Comment by emptyVoid** [comment]
> Out of interest is this also the potential cause for buildings that are collapsed and are rebuilt still acting as though collapsed in some instances?

It looks like the building "parts" are correctly restored during scenery repair at the end of day:
https://github.com/OpenApoc/OpenApoc/blob/5cb327e761953abe6bd1ce0c8f31a23dd38bdb89/game/state/city/scenery.cpp#L1662-L1665

Though I'm not sure what that `commonProperty` is, I believe it shouldn't affect Marsec/Megapol buildings.

**Comment by FilmBoy84** [comment]
Tested, works as intended
LGTM so merging
Great work as always @emptyvoid

**Pull request merged**
