### PR TITLE
Fix agents on init

### PR DESCRIPTION
**Pull request by RedRobin84**
This MR solves issues #1110  and #573 

- back to former 10 soldiers at the new game start (no missing equipment for soldiers #573)
- only humans as soldiers at the new game start (like in OG - solves #1110

### CODE REVIEW

**Comment by Kurtsley** [comment]
I could be wrong, but I was under the impression that you could start with Androids or hybrids based on your relationship with certain organizations.

**Comment by RedRobin84** [comment]
> I could be wrong, but I was under the impression that you could start with Androids or hybrids based on your relationship with certain organizations.

That was exactly what I was thinking, but tried starting several new games in original game and never got an Android or a Mutant. I think there should be only hirable agents based on relations with Mutant Aliance (Hybrids) and S.E.L.F. (Androids), but not starting agents.

**Comment by FilmBoy84** [comment]
@RedRobin84 Many thanks for this PR

Can you run a CLANG Format pass (LLVM 14) on it though please to stop the Linting errors

See also
https://www.ufopaedia.org/index.php/Coding_Style_(OpenApoc)

**Comment by RedRobin84** [comment]
> Can you run a CLANG Format pass (LLVM 14) on it though please to stop the Linting errors

Yes, sorry overlooked that. Thanks for the link, should be ok now.

**Comment by FilmBoy84** [comment]
> 

No problem, welcome aboard and thanks once more for the PR - Merged

**Pull request merged**
