### PR TITLE
Improved performance of city strategy view mode

### PR DESCRIPTION
**Pull request by redv**
The city strategy view mode on steroids.

### CODE REVIEW

**Comment by makus82** [comment]
what exactly improved?=]

**Comment by redv** [comment]
FPS higher than vanilla in DosBox ;P

**Comment by makus82** [comment]
RED look pls you off drag mechanics in last build !!!

**Comment by redv** [comment]
I need to rethink several stuff about implementation and do a several tests. This feature is not ready yet.

**Comment by makus82** [comment]
ooh good then =]

**Comment by redv** [comment]
Possible to decrease memory demand and additional speedup ~10-15%

**Pull request closed without merging**
