### PR TITLE
[interface] Fix selecting already-in-progress list item after change selection

### LINKED ISSUE #786: [interface] "Project too large", etc... message dialogues rises twice
When I try to start construction of large item in small workshop the error message dialogue shows twice.

It's non critical interface bug.

### PR DESCRIPTION
**Pull request by Atrosha**
Fixes `researchselection` when already-in-progress list item unable to select after changing selection.

Found this bug and fix it while trying to fix #786

### CODE REVIEW

**Comment by JonnyH** [comment]
Huh, it looks like you've somehow replaced every single file in git and added executable permissions.

What OS are you running? If on linux/macos make sure you didn't "chmod" things.

It might be easier if you just reset the whole repository back to the current OPenApoc 'master', then cherry-pick the specific change you've made (sha 8ec132e by the look of it) on top of that?

**Comment by Atrosha** [comment]
It seems I ruined my fork by commiting to it from NTFS disk earlier.
For now I fetch my fork to Linux home with ext4 partition but problem persist.

**Comment by JonnyH** [comment]
Yeah, ntfs doesn't support unix permissions well, so using ntfs on linux causes issues like this.

If you were running on windows, git then /knows/ unix permissions aren't supported, so ignores it :P

**Comment by Atrosha** [comment]
`git-clang-format` doesn't work properly.

**Pull request merged**
