### PR TITLE
scale weapon range correctly in vehicle equipment sheet

### PR DESCRIPTION
**Pull request by FranciscoDA**
As discussed in the discord: the range values in apoc's data file seem to be in half-metres. This fix should scale them accordingly while still displaying the value in tiles, as intended (related issue #361)

### CODE REVIEW

**Comment by FilmBoy84** [comment]
Many thanks Francisco
I'll grab the build tonight and check out each UFOPedia entry to see if behaviour is uniform across all weapons
If all OK, ill merge straight away as it's not really a fix that's going to break anything :D

**Comment by FilmBoy84** [comment]
OK, i've done some testing
It appears RANGE is still double what it should be
Additionally, Fire Rates are slower than OG so there's an additional problem there

Using the Justice Missile as an example
Here's the OG stats
image
Here's the same in OpenApoc
image

**Comment by FilmBoy84** [comment]
It get's even wierder on the prophet stats

OG
image

OpenApoc
image

**Comment by FranciscoDA** [comment]
I've fixed the range thing in the ufopaedia. I'm not really sure about the fire rate since the UI is using the same calculations as the game itself.

To match the values displayed in vanilla we need to double the amount of ticks per second or to halve the fire_delay. Of course it could turn out that we're doing the calculations correctly and it's only the ufopaedia of the original game showing incorrect stats. In any case I'd rather have the ufopaedia reflect the real in-game stats

**Comment by FilmBoy84** [comment]
@FranciscoDA The ticks per second is an interesting issue
Curiously issue #243 suggests that OpenApoc is currently working at half the speed it should be

It would be good to get @JonnyH 's opinion on this. Do we double the ticks per second and potentially resolve both issues?

**Comment by FilmBoy84** [comment]
Merging for @FranciscoDA as the code is fine and no bugs found.
We need a new issue and pull request for solving the issue with rate of fire found as part of this pull
I'll try to find a solution, but as JonnyH has pointed out, there's a fundamental issue with ticks-per-second that needs some substantial work to resolve.

**Pull request merged**
