### PR TITLE
Clean README formatting

### PR DESCRIPTION
**Pull request by rogersachan**
This pull request does a number of cosmetic fixes to the README, including the following:
* Properly spaced headers
* No trailing whitespace
* Consistently formatted lists
* Removed underscores in headers
* Fix the grammar in the tweet button
* Remove stray html breaks.
* Further grammar fixes
* Upgraded a bunch of URLs to HTTPS and fixed a broken link

### CODE REVIEW

**Comment by rogersachan** [comment]
Could I suggest trimming the number of buttons on the README? It's really overkill to have 20 lines (code) of just buttons.

This PR doesn't do that, so if they need to stay this should not be an issue.

**Comment by JonnyH** [comment]
I kind agree about the buttons - I kinda see github as developer focused - having a link to the latest build (build /status/ shouldn't be needed as such - as the builds should be verified before the PR is merged...), and a link to the website (from which you can get to the forums, IRC, other social media links etc.) should be sufficient... right?

Comments anyone else?

**Comment by makus82** [comment]
we need all beacose you dont know when and how )

**Comment by makus82** [comment]
..we can remove issues and trello buttons

**Comment by makus82** [comment]
readme read usually who newcomers so why not to output all possible info?)

**Comment by Thunderforge** [comment]
I was just thinking of creating a pull request for cleaning up the Readme. Is this something that can be merged? Or are there still outstanding issues (possibly ones that other people could do for this PR)?

**Pull request merged**
