### PR TITLE
cityscape UI text

### PR DESCRIPTION
**Pull request by SiemensSchuckert**
display selected organisations relation to X-COM

display selected Vehicle name and owner (https://github.com/OpenApoc/OpenApoc/issues/328)

display Physicists project progress

display Engineers project progress

display Biochemists project progress

display Soldiers rank and training assignment

### CODE REVIEW

**Comment by makus82** [comment]
its ... 0o tooltips? great work! @SiemensSchuckert

**Comment by redv** [comment]
Good addition, but a bug found.
Switching between organization's groups should at least clear the tips area.
orggroups

**Comment by SiemensSchuckert** [comment]
Thanks! fixed relation display.

**Comment by redv** [comment]
OK. But the fix #252 better done in a separate commit (or branch).

**Pull request merged**
