### PR TITLE
added hotkeys to ufopaedia

### PR DESCRIPTION
**Pull request by redv**
fixed issue #250 "We need add hotkeys in to ufopedia"

### CODE REVIEW

**Comment by makus82** [comment]
Strange test this and hotkeys dont work 
https://ci.appveyor.com/project/OpenApoc/openapoc/build/0.0.26

**Comment by redv** [comment]
This link leads to the "Pull request #293 - workaround for vehicle update & die" build.
Right link is https://ci.appveyor.com/project/OpenApoc/openapoc/build/0.0.25

**Comment by makus82** [comment]
but my link its build after hotkeys should it to include all prev commits?

**Comment by redv** [comment]
No. Because they are different branches.

**Pull request merged**
