### PR TITLE
Add option to left click icon to open equip menu

### PR DESCRIPTION
**Pull request by Kurtsley**
Addresses #1127 by adding an option to open the agent or vehicle equip screen by left clicking the icon. This restores the functionality from the original game where it was possible to right OR left click the icon to open the equip menu. To be clear, this option does not remove the ability to open the equip menu using right click, it just adds the left click and is disabled by default.

### CODE REVIEW

**Comment by Kurtsley** [comment]
Actually, should this be lumped in with the vanilla cityscape controls?

**Comment by FilmBoy84** [comment]
> Actually, should this be lumped in with the vanilla cityscape controls?

Probably an idea to
The options menu is not the best ordering at the moment
But if we try and get some coherency going forward it will save the job of doing a massive reordering later :D

**Comment by Kurtsley** [comment]
I will look into that reorder. Probably a separate PR though.

**Comment by FilmBoy84** [comment]
Agreed, best as another PR

Just a heads up, this now has conflicts with the changes added by #1150 on merger

**Pull request merged**
